---
title: "p8105_hw5_mm5351"
author: "Martha Mulugeta"
date: "11/6/2019"
output: github_document
---

**Problem 1**
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

```{r}
iris_fill = function(x) {
  if (is.numeric(x)) {
    replace_na(x, mean(x, na.rm = TRUE))
  } else if (is.character(x)) {
    replace_na(x, "virginica")
  }
}

output = map_df(iris_with_missing, iris_fill) 
```

**Problem 2**
```{r}
study_df = tibble(
participant = list.files(path = "./Data", pattern = ".csv",  all.files = TRUE, full.names = TRUE)) %>% 
  mutate(data = map(participant, read_csv)) %>% 
  unnest() 

study_df = 
  study_df %>%
  separate(col = participant, sep = "_", into = c("arm", "subjectID")) %>% 
  mutate(
    arm = str_replace(arm, "./Data/", ""),
    subjectID = str_replace(subjectID, ".csv", "")
  ) %>% 

 pivot_longer(
    week_1:week_8,
    names_to = "week",
    values_to = "observation"
  ) %>%
  mutate(week = str_replace(week, "week_", "")) %>%
  unite(participant, arm, subjectID, sep = " ", remove = FALSE) %>% 
  group_by(week, participant) 
  
study_df %>%  
ggplot(aes(x = week, y = observation, color = participant, group = participant)) +
  geom_line() + 
     labs(
    title = "Observations Over Time",
    x = "Week",
    y = "Observation")
```

**Problem 3**
```{r}
sim_regression = function(n = 30, beta0 = 2, beta1 = 0) {
   sim_data = tibble(
    x = rnorm(n),
    y = beta0 + beta1 * x + rnorm(n, 0, sqrt(50))
  )
  
fit = lm(y ~ x, data = sim_data) %>% 
    broom::tidy()
}

```

```{r}
sim_results = 
  tibble(beta1 = c(0, 1, 2, 3, 4, 5, 6)) %>% 
  mutate(
    output_lists = map(.x = beta1, ~ rerun(10000, sim_regression(beta1 = .x))),
    estimate_dfs = map(output_lists, bind_rows)) %>% 
  select(-output_lists) %>% 
  unnest(estimate_dfs)
```


